### PR TITLE
Added support for requesting soft deleted records

### PR DESCRIPTION
**Pull request by danderson00**
Added includeDeleted function to Query. Adds includeDeleted property to object returned by getComponents.

### CODE REVIEW

**Comment by danderson00** [comment]
@shrishrirang Let's have a quick chat about this, it might have a small impact on the js client. Plan to release it as 0.1.0 so we can prevent it from impacting the current version of the client. (^0.0.1 won't install 0.1.0)

**Comment by danderson00** [comment]
Resolves https://github.com/Azure/azure-query-js/issues/18

**Comment by shrishrirang** [comment]
Looks good. js-client can start using this now instead of handcrafting the URL to contain the __includeDeleted param.

**Comment by m-andersen** [comment]
Hi. I have issues getting this to work. Can you please make me a full example on how to use this feature? E.g. do a read from a table to include soft deleted entries as well.

**Comment by danderson00** [comment]
From the server, you should just be able to say `req.azureMobile.tables('tablename').includeDeleted().read().then(...)`. Let me know if this doesn't work.

**Pull request merged**
